### PR TITLE
Feature increase speed by score

### PR DESCRIPTION
**Pull request by bleachjade**
👉 Please checkout these gameplay features:
✅ Added a function to increase speed by player's score
✅ Changed a material of a box between the Pipe prefab

### CODE REVIEW

**Comment by Wijantra** [comment]
It works. I already tested.

**Comment by theethaj** [comment]
It works.

**Comment by boom210232** [comment]
Ok 👍 👌 ✅

**Comment by chayoto777** [comment]
It works good job.

**Comment by boom210232** [comment]
For democracy 4/7 agree!

**Pull request merged**
