### PR TITLE
😘 Endless Pipes and Border with deallocating the used Pipes and Border

### PR DESCRIPTION
**Pull request by keyboard2543**
👉 Please checkout these gameplay features:
✅ Implement the game for the endless gameplay.
✅ Deallocating the used gameObjects by Destroy them.

### CODE REVIEW

**Comment by bleachjade** [comment]
Nice one! I've already test it and it work!

**Comment by kabilza** [comment]
That's good! Works perfectly fine!

**Comment by boom210232** [comment]
LGTM Let's continue.

**Comment by Wijantra** [comment]
It works well.

**Comment by theethaj** [comment]
It works.

**Comment by chayoto777** [comment]
Good job bro!

**Comment by boom210232** [comment]
Seem like everyone agree with it. Let's merge!

**Pull request merged**
